import type { Messages, FormatHelpers } from './types'

export const messages: Messages = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update',
    loading: 'Loading...',
    saving: 'Saving...',
    deleting: 'Deleting...',
    sending: 'Sending...',
    updating: 'Updating...',
    select: 'Select',
    optional: 'Optional',
    required: 'Required',
    all: 'All',
    custom: 'Custom',
    day: 'Day',
    confirmDelete: 'Are you sure you want to delete?',
    locale: 'en-US',
    uncategorized: 'Uncategorized',
  },

  nav: {
    home: 'Home',
    reports: 'Reports',
    budgets: 'Budgets',
    categories: 'Categories',
    recurring: 'Recurring',
    profile: 'Profile',
    signOut: 'Sign Out',
  },

  home: {
    title: 'Expense Tracker',
    subtitle: 'Manage your finances with ease',
    addTransaction: 'Add Transaction',
  },

  balance: {
    totalBalance: 'Total Balance',
    currentBalance: 'Current balance',
    income: 'Income',
    totalIncome: 'Total income',
    expenses: 'Expenses',
    totalExpenses: 'Total expenses',
  },

  transaction: {
    title: 'Transaction',
    transactions: 'Transactions',
    addTitle: 'Add Transaction',
    editTitle: 'Edit Transaction',
    addDescription: 'Add a new income or expense transaction.',
    editDescription: 'Update your transaction details.',
    type: 'Type',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    paymentMethod: 'Payment Method',
    description: 'Description',
    selectCategory: 'Select category',
    selectPaymentMethod: 'Select payment method',
    optionalDescription: 'Optional description...',
    income: 'Income',
    expense: 'Expense',
    noTransactions: 'No transactions found',
    addFirstTransaction: 'Add your first transaction',
    allTypes: 'All Types',
    allCategories: 'All Categories',
    deleteConfirm: 'Are you sure you want to delete this transaction?',
  },

  paymentMethods: {
    cash: 'Cash',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    bankTransfer: 'Bank Transfer',
    pix: 'PIX',
    other: 'Other',
  },

  budget: {
    title: 'Budget',
    addTitle: 'Add Budget',
    editTitle: 'Edit Budget',
    addDescription: 'Set a budget for a category.',
    editDescription: 'Update your budget.',
    spent: 'Spent',
    remaining: 'Remaining',
    overBudget: 'Over budget',
    nearLimit: 'Near limit',
    onTrack: 'On track',
    noBudgets: 'No budgets found',
    addFirstBudget: 'Add your first budget',
    month: 'Month',
    year: 'Year',
    amount: 'Amount',
    subtitle: 'Track your spending limits for',
    addGoalTitle: 'Add Budget Goal',
    addGoalDescription: 'Set a monthly spending limit for a category.',
    budgetLimit: 'Budget Limit ($)',
    selectCategory: 'Select category',
  },

  category: {
    title: 'Category',
    categories: 'Categories',
    addTitle: 'Add Category',
    editTitle: 'Edit Category',
    deleteTitle: 'Delete Category',
    deleteConfirm: 'Are you sure you want to delete the category',
    name: 'Name',
    type: 'Type',
    icon: 'Icon',
    color: 'Color',
    noCategories: 'No categories found',
    addFirstCategory: 'Add your first category',
    subtitle: 'Manage your expense and income categories',
    income: 'Income Categories',
    incomeDescription: 'Categories for tracking your income',
    expense: 'Expense Categories',
    expenseDescription: 'Categories for tracking your expenses',
    noIncome: 'No income categories yet',
    noExpense: 'No expense categories yet',
    cannotDelete: 'Cannot delete default categories',
    addDescription: 'Create a new custom category for organizing your transactions.',
    editDescription: 'Update the category details.',
    namePlaceholder: 'e.g., Groceries',
    selectType: 'Select type',
    iconLabel: 'Icon (Emoji)',
    iconPlaceholder: 'e.g., 🛒',
    iconHelp: 'Enter an emoji to represent this category',
    create: 'Create',
  },

  categories: {
    salary: 'Salary',
    freelance: 'Freelance',
    investments: 'Investments',
    other: 'Other',
    food: 'Food',
    transport: 'Transport',
    housing: 'Housing',
    utilities: 'Utilities',
    entertainment: 'Entertainment',
    healthcare: 'Healthcare',
    education: 'Education',
    shopping: 'Shopping',
  },

  recurring: {
    title: 'Recurring',
    addTitle: 'Add Recurring',
    editTitle: 'Edit Recurring',
    dayOfMonth: 'Day of Month',
    isActive: 'Active',
    active: 'Active',
    inactive: 'Inactive',
    noRecurring: 'No recurring transactions found',
    addFirstRecurring: 'Add your first recurring transaction',
    upcomingPayments: 'Upcoming Payments',
    for: 'for',
    markAsPaid: 'Mark as Paid',
    markPaid: 'Mark Paid',
    dueDate: 'Due Date',
    subtitle: 'Manage your monthly recurring expenses and income',
    upcomingDescription: 'Mark payments as paid when completed',
    templatesDescription: 'Manage your recurring transaction templates',
    addTransactionTitle: 'Add Recurring Transaction',
    editTransactionTitle: 'Edit Recurring Transaction',
    addTransactionDescription: 'Set up a transaction that repeats monthly.',
    editTransactionDescription: 'Update your recurring transaction.',
    amount: 'Amount ($)',
    day: 'Day',
    descriptionPlaceholder: 'e.g., Netflix subscription, Rent payment...',
    selectPaymentMethod: 'Select payment method',
    viewAll: 'View All',
    overdue: 'Overdue',
    overdueLabel: 'overdue',
    upcoming: 'upcoming',
    overduePayments: 'Overdue Payments',
    upcomingThisMonth: 'Upcoming This Month',
    dueToday: 'Due today',
    dueTomorrow: 'Due tomorrow',
    daysOverdue: '{count, plural, =1 {# day overdue} other {# days overdue}}',
    daysUntilDue: 'in {count, plural, =1 {# day} other {# days}}',
    andXMore: '+ {count} more...',
    paymentMarkedAsPaid: 'Payment marked as paid successfully',
    errorMarkingPayment: 'Error marking payment as paid',
  },

  reports: {
    title: 'Reports',
    subtitle: 'View and analyze your finances',
    categoryBreakdown: 'Category Breakdown',
    monthlyTrend: 'Monthly Trend',
    yearlyOverview: 'Yearly Overview',
    selectMonth: 'Select month',
    selectYear: 'Select year',
    noDataAvailable: 'No data available for this period',
    paymentMethods: 'Payment Methods',
    transactionCount: 'transactions',
    dailyTrend: 'Daily Trend',
    incomeByCategory: 'Income by Category',
    expensesByCategory: 'Expenses by Category',
    noIncomeData: 'No income for this period',
    noExpenseData: 'No expenses for this period',
  },

  profile: {
    title: 'Profile',
    settings: 'Profile Settings',
    subtitle: 'Manage your profile and WhatsApp bot configuration',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Enter your display name',
    email: 'Email',
    emailCannotChange: 'Email cannot be changed. Contact support if needed.',
    saveChanges: 'Save Changes',
    updateFailed: 'Failed to update profile',
    whatsappNumbers: 'WhatsApp Numbers',
    authorizedGroups: 'Authorized Groups',
    language: 'Language',
  },

  whatsapp: {
    title: 'WhatsApp Configuration',
    subtitle: 'Manage authorized WhatsApp numbers and their permissions',
    addNumber: 'Add Number',
    editNumber: 'Edit WhatsApp Number',
    addNumberTitle: 'Add WhatsApp Number',
    editNumberSubtitle: 'Update the WhatsApp number and its permissions.',
    addNumberSubtitle: 'Add a WhatsApp number that can interact with the bot. Set permissions to control what this number can do.',
    noNumbers: 'No WhatsApp numbers added yet.',
    name: 'Name / Label',
    namePlaceholder: 'e.g., Spouse, John, Me',
    nameHelp: 'A label to identify this number',
    number: 'WhatsApp Number',
    numberPlaceholder: '5511999999999',
    numberHelp: 'Enter the full WhatsApp number including country code (e.g., 5511999999999)',
    isPrimary: 'Set as primary number',
    onlyOnePrimary: 'Only one number can be primary.',
    primary: 'Primary',
    permissions: 'Permissions',
    permissionView: 'View Transactions',
    permissionViewDesc: 'Can view all transactions and balances',
    permissionAdd: 'Add Transactions',
    permissionAddDesc: 'Can add new income and expenses',
    permissionEdit: 'Edit Transactions',
    permissionEditDesc: 'Can modify existing transactions',
    permissionDelete: 'Delete Transactions',
    permissionDeleteDesc: 'Can delete transactions',
    permissionBudgets: 'Manage Budgets',
    permissionBudgetsDesc: 'Can create, edit, and delete budgets',
    permissionReports: 'View Reports',
    permissionReportsDesc: 'Can view financial reports and analytics',
    view: 'View',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    budgets: 'Budgets',
    reports: 'Reports',
    deleteConfirm: 'Are you sure you want to delete this WhatsApp number?',
    deleteFailed: 'Failed to delete WhatsApp number',
    invalidNumber: 'Please enter a valid WhatsApp number',
    saveFailed: 'Failed to save WhatsApp number',
  },

  groups: {
    title: 'Authorized Groups',
    subtitle: 'WhatsApp groups where the bot is authorized to respond to messages',
    noGroups: 'No authorized groups yet.',
    noGroupsHelp: 'Add the bot to a group to see it here. Groups are automatically authorized when added by you.',
    unknownGroup: 'Unknown Group',
    autoAuthorized: 'Auto-authorized',
    active: 'Active',
    inactive: 'Inactive',
    addedBy: 'Added by',
    lastMessage: 'Last message',
    never: 'Never',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    weeksAgo: 'w ago',
    activate: 'Activate',
    deactivate: 'Deactivate',
    deleteConfirm: 'Are you sure you want to remove authorization for',
    updateFailed: 'Failed to update group status',
    deleteFailed: 'Failed to delete authorized group',
  },

  auth: {
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    newPassword: 'New Password',
    passwordRequirement: 'Must be at least 6 characters',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordMismatch: 'Passwords do not match',
    emailRequired: 'Email is required',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signInWithEmail: 'Sign in with Email',
    signUpWithEmail: 'Sign up with Email',
    backToLogin: 'Back to login',
    loginDescription: 'Choose your preferred login method',

    passwordResetError: 'Failed to send reset email. Please try again.',
    magicLinkError: 'Failed to send magic link. Please try again.',

    // Forgot Password (nested structure with label for link)
    forgotPassword: {
      label: 'Forgot password?',
      title: 'Forgot Password?',
      description: "Enter your email and we'll send you a link to reset your password",
      sendLink: 'Send Reset Link',
      info: "You'll receive an email with a secure link to reset your password. The link expires in 1 hour.",
      success: {
        title: 'Check your email!',
        description: "We've sent a password reset link to {email}. Click the link in the email to create a new password.",
        note: "Didn't receive the email? Check your spam folder or try again.",
      },
      sendAnother: 'Send another email',
    },

    // Reset Password (nested structure)
    resetPassword: {
      title: 'Reset Password',
      description: 'Choose a new password for your account',
      button: 'Reset Password',
      invalidToken: 'Invalid or expired reset link. Please request a new one.',
      sessionError: 'Unable to verify reset link. Please try again.',
      error: 'Failed to reset password. Please try again.',
      success: {
        title: 'Password reset successful!',
        description: 'Your password has been updated. Redirecting you to login...',
      },
      invalidTitle: 'Invalid Reset Link',
      linkExpired: 'Password reset links expire after 1 hour for security. Please request a new link.',
      requestNew: 'Request New Link',
    },

    // Magic Link (nested structure with label for tab)
    magicLink: {
      label: 'Magic Link',
      info: "We'll send you a secure login link via email. No password needed!",
      sendLink: 'Send Magic Link',
      success: {
        title: 'Check your email!',
        description: "We've sent a magic link to {email}. Click the link in the email to log in instantly.",
        note: "The link will expire in 1 hour. Didn't receive it? Check your spam folder.",
      },
      sendAnother: 'Send another link',
    },
  },

  settings: {
    account: {
      title: 'Account Settings',
      subtitle: 'Manage your account information and data',
      accountInfo: 'Account Information',
      dataSummary: 'Your Data Summary',
      transactions: 'Transactions',
      categories: 'Categories',
      budgets: 'Budgets',
      recurringPayments: 'Recurring Payments',
      whatsappNumbers: 'WhatsApp Numbers',
      authorizedGroups: 'Authorized Groups',
      dataRights: 'Your Data Rights (LGPD)',
      dataRightsDescription: 'According to Brazilian data protection law (LGPD), you have the right to:',
      rightAccess: 'Access your personal data',
      rightCorrect: 'Correct inaccurate data',
      rightDelete: 'Request deletion of your data',
      rightPortability: 'Data portability',
      dangerZone: 'Danger Zone',
      deleteAccount: 'Delete My Account',
      deleteAccountWarning: 'Permanently delete your account and all associated data. This action cannot be undone.',
      deleteAccountInfo: 'This will permanently delete:',
      deleteAllTransactions: 'All your transactions',
      deleteAllBudgets: 'All budgets and categories',
      deleteWhatsappIntegration: 'WhatsApp integration',
      deleteAiUsageHistory: 'AI usage history',
      accountWillBeInaccessible: 'Your account will be permanently inaccessible',
      confirmDeletion: 'To confirm deletion, type DELETE MY ACCOUNT below:',
      deleteForever: 'Delete Forever',
      deleting: 'Deleting...',
      deletionSuccess: 'Your account has been deleted successfully. Redirecting...',
      deletionFailed: 'Failed to delete account. Please try again.',
      confirmationRequired: 'Please type DELETE MY ACCOUNT to confirm',
    },
    notifications: {
      title: 'Notification Preferences',
      reengagement_label: 'Re-engagement Messages',
      reengagement_description: 'Receive reminders when inactive (goodbye message and weekly review)',
      info_note: 'Note: This preference does not affect onboarding tips you receive when completing tiers.',
      success_toast: 'Preferences saved',
      error_toast: 'Failed to save preferences. Please try again.',
    },
  },

  months: {
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
  },

  table: {
    date: 'Date',
    description: 'Description',
    category: 'Category',
    paymentMethod: 'Payment Method',
    amount: 'Amount',
    type: 'Type',
    actions: 'Actions',
  },

  onboarding: {
    progress: 'Step {current} of {total}',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    skipTour: 'Skip Tour',
    getStarted: 'Get Started',
    complete: 'Complete',

    welcome: {
      title: 'Welcome',
      heading: 'Welcome to NexFinApp!',
      intro: 'Your personal finance assistant via WhatsApp',
      feature1Title: 'Track Expenses Easily',
      feature1Desc: 'Just send a message like "Spent 50 on food"',
      feature2Title: 'Smart OCR',
      feature2Desc: 'Send photos of receipts or bank SMS',
      feature3Title: 'Monthly Budgets',
      feature3Desc: 'Set limits and get alerts',
    },

    whatsapp: {
      title: 'WhatsApp',
      heading: 'Connect Your WhatsApp',
      description: 'Manage finances directly from WhatsApp',
      explanation: 'Add your WhatsApp number to start receiving updates and interact with the bot.',
      instructions: 'Click the button below to add your WhatsApp number',
      addButton: 'Add WhatsApp Number',
      connected: 'WhatsApp Connected!',
    },

    category: {
      title: 'Categories',
      heading: 'Create Your First Category',
      description: 'Organize your expenses',
      explanation: 'Categories help you organize and track different types of expenses.',
      tip: 'Pro Tip:',
      tipDetail: 'Common categories include: Food, Transport, Rent, Entertainment',
      goToCategories: 'Go to Categories',
    },

    expense: {
      tutorialTitle: 'Add Your First Expense',
      tutorialDescription: 'Click here to add a transaction. You can do this via WhatsApp or the web interface.',
    },

    features: {
      title: 'Features',
      heading: 'Powerful Features',
      description: 'What you can do',
      explanation: 'Here are the key features to help you manage your finances:',
      tutorialTitle: 'Explore All Features',
      tutorialDescription: 'Access reports, budgets, categories, and recurring transactions from here. Start exploring!',

      naturalLanguage: {
        title: 'Natural Language',
        description: 'Just talk naturally, no commands needed',
        example: '"Spent 50 on lunch today"',
      },

      ocr: {
        title: 'OCR for Bank SMS',
        description: 'Send photos of bank messages for automatic expense extraction',
        example: 'Just send a photo of your bank SMS!',
      },

      budgets: {
        title: 'Monthly Budgets',
        description: 'Set spending limits and get alerts when you\'re close',
      },
    },
  },
}

export const formatHelpers: FormatHelpers = {
  formatCurrency: (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(value)
  },

  formatDate: (date: Date | string) => {
    const dateObj = typeof date === 'string' ? new Date(date) : date
    return new Intl.DateTimeFormat('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
    }).format(dateObj)
  },

  formatNumber: (value: number) => {
    return new Intl.NumberFormat('en-US').format(value)
  },

  getMonthName: (month: number) => {
    const monthNames = [
      messages.months.january,
      messages.months.february,
      messages.months.march,
      messages.months.april,
      messages.months.may,
      messages.months.june,
      messages.months.july,
      messages.months.august,
      messages.months.september,
      messages.months.october,
      messages.months.november,
      messages.months.december,
    ]
    return monthNames[month - 1] || ''
  },

  getCurrencySymbol: () => '$',
}
