import type { Messages, FormatHelpers } from './types'

export const messages: Messages = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update',
    loading: 'Loading...',
    saving: 'Saving...',
    deleting: 'Deleting...',
    sending: 'Sending...',
    updating: 'Updating...',
    select: 'Select',
    optional: 'Optional',
    required: 'Required',
    all: 'All',
    custom: 'Custom',
    day: 'Day',
    days: 'days',
    current: 'Current',
    confirmDelete: 'Are you sure you want to delete?',
    locale: 'en-US',
    uncategorized: 'Uncategorized',
  },

  nav: {
    home: 'Home',
    reports: 'Reports',
    budgets: 'Budgets',
    categories: 'Categories',
    recurring: 'Recurring',
    profile: 'Profile',
    signOut: 'Sign Out',
    // New grouped navigation
    overview: 'Overview',
    dashboard: 'Dashboard',
    creditCards: 'Credit Cards',
    installments: 'Installments',
    manageCreditCards: 'Manage Credit Cards',
    settings: 'Settings',
    paymentMethods: 'Payment Methods',
  },

  home: {
    title: 'NexFinApp',
    subtitle: 'Manage your finances with ease',
    addTransaction: 'Add Transaction',
  },

  balance: {
    totalBalance: 'Total Balance',
    currentBalance: 'Current balance',
    income: 'Income',
    totalIncome: 'Total income',
    expenses: 'Expenses',
    totalExpenses: 'Total expenses',
  },

  dashboard: {
    financialOverview: 'Financial Overview',
    commitments: 'Upcoming Commitments',
    viewAll: 'View all',
    categoryBreakdown: 'Category Breakdown',
    moreCategories: '+{count} categories',
    moreCommitments: '+{count} commitments',
    noCommitments: 'No upcoming commitments',
    noCommitmentsHint: 'You have no recurring payments or pending installments',
  },

  creditCards: {
    title: 'Manage Credit Cards',
    subtitle: 'Configure your credit and debit cards',
    addCard: 'Add New Card',
    editCard: 'Edit Card',
    deleteCard: 'Delete Card',
    deleteConfirm: 'Are you sure you want to delete this card?',
    deleteWarning: 'This action cannot be undone. All transactions associated with this card will remain in the system.',
    noCreditCards: 'You have no cards yet',
    noCreditCardsHint: 'Add your credit cards to track spending, budgets, and installments',
    addFirstCard: 'Add First Card',
    creditMode: 'Credit Mode',
    simpleMode: 'Debit Mode',
    creditModeDescription: 'Track budgets, statement periods, and installments',
    simpleModeDescription: 'Record transactions without advanced credit features',
    budget: 'Budget',
    closingDay: 'Closing Day',
    dueDay: 'Due Day',
    noBudgetSet: 'No budget',
    notConfigured: 'Not configured',
    helpTitle: 'Understand the modes',
    day: 'Day {day}',
  },

  paymentMethods: {
    title: 'Payment Methods',
    subtitle: 'Manage your bank accounts and other payment methods',
    addMethod: 'Add Payment Method',
    editMethod: 'Edit Payment Method',
    deleteMethod: 'Delete Payment Method',
    deleteConfirm: 'Are you sure you want to delete this payment method?',
    deleteWarning: 'All transactions associated with this method will remain in the system.',
    noMethods: 'You have no payment methods yet',
    noMethodsHint: 'Add bank accounts, PIX keys, or other payment methods to track your finances',
    addFirstMethod: 'Add First Method',
    methodName: 'Method Name',
    methodNamePlaceholder: 'e.g., Checking Account, Savings, Nubank',
    methodNameRequired: 'Method name is required',
    methodType: 'Type',
    selectType: 'Select type',
    types: {
      cash: 'Cash',
      pix: 'PIX',
      other: 'Other',
      credit: 'Credit Card',
      debit: 'Debit Card',
    },
    helpTitle: 'About Payment Methods',
    helpDescription: 'Track your bank accounts, digital wallets, and other payment methods. Credit cards should be managed in the Credit Cards section.',
    addMethodDescription: 'Add a new bank account, PIX key, or other payment method',
    editMethodDescription: 'Update your payment method information',
    addSuccess: 'Payment method added successfully',
    addError: 'Error adding payment method',
    editComingSoon: 'Edit functionality coming soon',
    editError: 'Error updating payment method',
    deleteSuccess: 'Payment method deleted successfully',
    deleteError: 'Error deleting payment method',
    createdOn: 'Created on',
  },

  transaction: {
    title: 'Transaction',
    transactions: 'Transactions',
    addTitle: 'Add Transaction',
    editTitle: 'Edit Transaction',
    addDescription: 'Add a new income or expense transaction.',
    editDescription: 'Update your transaction details.',
    type: 'Type',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    paymentMethod: 'Payment Method',
    description: 'Description',
    selectCategory: 'Select category',
    selectPaymentMethod: 'Select payment method',
    suggestedPaymentMethods: 'Suggested',
    willBeCreated: 'will be created',
    paymentMethodError: 'Failed to create payment method',
    optionalDescription: 'Optional description...',
    income: 'Income',
    expense: 'Expense',
    noTransactions: 'No transactions found',
    addFirstTransaction: 'Add your first transaction',
    allTypes: 'All Types',
    allCategories: 'All Categories',
    deleteConfirm: 'Are you sure you want to delete this transaction?',
    deleteAutoGeneratedTitle: 'Delete auto-generated payment?',
    deleteAutoGeneratedMessage: 'This transaction was auto-generated. Are you sure you want to delete it?',
    deleteAutoGeneratedCancel: 'Cancel',
    deleteAutoGeneratedConfirm: 'Delete',
    autoPaymentEdited: 'Auto-generated payment edited',
    autoPaymentDeleted: 'Auto-generated payment deleted',
    autoGenerated: 'Auto-generated',
    installments: 'Installments',
    installmentsDescription: 'Installment options available',
    installment: {
      toggleLabel: 'Installment purchase?',
      totalAmountLabel: 'Total Amount',
      totalAmountPlaceholder: '0.00',
      installmentsLabel: 'Number of Installments',
      monthlyPaymentLabel: 'Monthly Payment',
      monthlyPaymentFormat: 'R$ {amount} / month',
      firstPaymentLabel: 'First Payment Date',
      lastPaymentNote: '(Last installment: R$ {amount})',
      createSuccess: 'Installment created successfully!',
      createSuccessDetails: '{description} - R$ {totalAmount} in {installments}x of R$ {monthlyAmount}',
      createError: 'Error creating installment: {error}',
      validationAmountPositive: 'Amount must be greater than zero',
      validationAmountRequired: 'Required field',
      validationInstallmentsMin: 'Minimum 1 installment',
      validationInstallmentsMax: 'Maximum 60 installments',
      validationDateRequired: 'Required field',
      validationPastDateWarning: 'Past date. Confirm?',
      validationSimpleModeError: 'This card does not support installments',
      merchantLabel: 'Store/Merchant',
      merchantPlaceholder: 'Ex: Best Buy',
    },
  },

  paymentMethodTypes: {
    cash: 'Cash',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    bankTransfer: 'Bank Transfer',
    pix: 'PIX',
    other: 'Other',
    creditMode: 'Credit Mode',
    simpleMode: 'Debit Mode',
  },

  statementSettings: {
    title: 'Statement Settings',
    closingDayLabel: 'Closing Day',
    closingDayPlaceholder: 'Select day',
    notSet: 'Not set',
    currentPeriod: 'Current period: {start} - {end}',
    nextClosing: 'Next closing: {date} ({days} days)',
    saveButton: 'Save',
    successToast: 'Statement closing date set to day {day}',
    errorToast: 'Error saving settings. Please try again.',
    validationError: 'Closing day must be between 1 and 31',
    description: 'Set the day of the month when your statement closes (1-31)',
    helpText: 'This is the day your credit card statement closes each month',
  },

  budgetSettings: {
    title: 'Monthly Budget',
    label: 'Budget',
    placeholder: 'Enter amount (e.g., 2000)',
    notSet: 'Not set',
    helperText: 'Budget applies to statement period ({start} - {end})',
    saveButton: 'Save',
    removeButton: 'Remove Budget',
    successToast: 'Monthly budget set: {amount}',
    removedToast: 'Budget removed. Spending still tracked.',
    errorToast: 'Error saving budget. Please try again.',
    validationErrorNegative: 'Budget cannot be negative',
    validationErrorInvalid: 'Enter a valid amount',
    confirmZeroBudget: 'Budget of R$ 0 means no limit. Confirm?',
    confirmHighBudget: 'Budget of {amount}+. Confirm?',
    infoOverBudget: 'You have already spent {spent}, above budget of {budget}',
    setClosingDateFirst: 'Set statement closing date first to enable budget',
    tooltipTitle: 'About Monthly Budget',
    tooltipContent: 'Your monthly budget is different from your card limit. Set an amount you want to spend per statement period.',
    description: 'Set a personal budget for this card (separate from bank limit)',
  },

  paymentDueSettings: {
    title: 'Payment Due Date',
    dueAfterClosingLabel: 'Days after closing',
    dueAfterClosingPlaceholder: 'E.g., 10 days',
    notSet: 'Not set',
    previewDueDay: 'Payment will be due on the {day} of each month',
    nextPayment: 'Next payment: {date}',
    saveButton: 'Save',
    successToast: 'Payment due date set: {days} days after closing',
    errorToast: 'Error saving configuration. Please try again.',
    validationError: 'Due date must be between 1 and 60 days after closing',
    closingDayRequired: 'Set statement closing date first',
    setClosingDayButton: 'Set Closing Date',
    description: 'Set how many days after statement closes the payment is due',
    helpText: 'Example: if statement closes on the 5th and payment is due 10 days later, payment is on the 15th',
  },

  budget: {
    title: 'Budget',
    addTitle: 'Add Budget',
    editTitle: 'Edit Budget',
    addDescription: 'Set a budget for a category.',
    editDescription: 'Update your budget.',
    spent: 'Spent',
    remaining: 'Remaining',
    overBudget: 'Over budget',
    nearLimit: 'Near limit',
    onTrack: 'On track',
    noBudgets: 'No budgets found',
    addFirstBudget: 'Add your first budget',
    month: 'Month',
    year: 'Year',
    amount: 'Amount',
    subtitle: 'Track your spending limits for',
    addGoalTitle: 'Add Budget Goal',
    addGoalDescription: 'Set a monthly spending limit for a category.',
    budgetLimit: 'Budget Limit ($)',
    selectCategory: 'Select category',
    // Story 2.8: Budget with Installments
    statementPeriod: 'Statement period: {start} - {end}',
    totalSpent: 'Total spent',
    breakdown: 'Breakdown by category',
    categoryTotal: '{category}: {amount}',
    installmentPayment: '{description} (Payment {current}/{total})',
    regularTransaction: '{description}',
    uncategorized: 'Uncategorized',
    noExpenses: 'No expenses in this period',
    performanceNote: 'Calculated in {time}ms',
  },

  // Story 3.3: Budget Progress Dashboard
  budgetProgress: {
    title: 'Budget',
    period: 'Period: {start} - {end}',
    spent: 'Spent',
    remaining: '{amount} remaining',
    exceededBy: '{amount} over budget',
    percentageUsed: '{percentage}% of budget used',
    daysUntilClosing: '{days} days until closing',
    oneDayUntilClosing: '1 day until closing',
    closesToday: 'Closes today',
    closesTomorrow: 'Closes tomorrow',
    statusOnTrack: 'On track',
    statusNearLimit: 'Near limit',
    statusExceeded: 'Over budget',
    noBudgetSet: 'No budget set',
    noBudgetCTA: 'Set budget',
    noClosingDateSet: 'Configure closing date to track budget',
    noClosingDateCTA: 'Configure',
    noTransactions: 'No transactions in this period',
    errorLoading: 'Error loading budget. Please try again.',
    retryButton: 'Try again',
    spentOf: '{spent} of {budget}',
    noLimit: 'No limit set',
  },

  category: {
    title: 'Category',
    categories: 'Categories',
    addTitle: 'Add Category',
    editTitle: 'Edit Category',
    deleteTitle: 'Delete Category',
    deleteConfirm: 'Are you sure you want to delete the category',
    name: 'Name',
    type: 'Type',
    icon: 'Icon',
    color: 'Color',
    noCategories: 'No categories found',
    addFirstCategory: 'Add your first category',
    subtitle: 'Manage your expense and income categories',
    income: 'Income Categories',
    incomeDescription: 'Categories for tracking your income',
    expense: 'Expense Categories',
    expenseDescription: 'Categories for tracking your expenses',
    noIncome: 'No income categories yet',
    noExpense: 'No expense categories yet',
    cannotDelete: 'Cannot delete default categories',
    addDescription: 'Create a new custom category for organizing your transactions.',
    editDescription: 'Update the category details.',
    namePlaceholder: 'e.g., Groceries',
    selectType: 'Select type',
    iconLabel: 'Icon (Emoji)',
    iconPlaceholder: 'e.g., 🛒',
    iconHelp: 'Enter an emoji to represent this category',
    create: 'Create',
    systemBadge: 'System',
    cannotDeleteSystemCategory: 'System categories cannot be deleted',
    deleteSystemCategoryTooltip: 'System category cannot be deleted',
  },

  categories: {
    salary: 'Salary',
    freelance: 'Freelance',
    investments: 'Investments',
    other: 'Other',
    food: 'Food',
    transport: 'Transport',
    housing: 'Housing',
    utilities: 'Utilities',
    entertainment: 'Entertainment',
    healthcare: 'Healthcare',
    education: 'Education',
    shopping: 'Shopping',
  },

  recurring: {
    title: 'Recurring',
    addTitle: 'Add Recurring',
    editTitle: 'Edit Recurring',
    dayOfMonth: 'Day of Month',
    isActive: 'Active',
    active: 'Active',
    inactive: 'Inactive',
    noRecurring: 'No recurring transactions found',
    addFirstRecurring: 'Add your first recurring transaction',
    upcomingPayments: 'Upcoming Payments',
    for: 'for',
    markAsPaid: 'Mark as Paid',
    markPaid: 'Mark Paid',
    dueDate: 'Due Date',
    subtitle: 'Manage your monthly recurring expenses and income',
    upcomingDescription: 'Mark payments as paid when completed',
    templatesDescription: 'Manage your recurring transaction templates',
    addTransactionTitle: 'Add Recurring Transaction',
    editTransactionTitle: 'Edit Recurring Transaction',
    addTransactionDescription: 'Set up a transaction that repeats monthly.',
    editTransactionDescription: 'Update your recurring transaction.',
    amount: 'Amount ($)',
    day: 'Day',
    descriptionPlaceholder: 'e.g., Netflix subscription, Rent payment...',
    selectPaymentMethod: 'Select payment method',
    viewAll: 'View All',
    overdue: 'Overdue',
    overdueLabel: 'overdue',
    upcoming: 'upcoming',
    overduePayments: 'Overdue Payments',
    upcomingThisMonth: 'Upcoming This Month',
    dueToday: 'Due today',
    dueTomorrow: 'Due tomorrow',
    daysOverdue: '{count, plural, =1 {# day overdue} other {# days overdue}}',
    daysUntilDue: 'in {count, plural, =1 {# day} other {# days}}',
    andXMore: '+ {count} more...',
    paymentMarkedAsPaid: 'Payment marked as paid successfully',
    errorMarkingPayment: 'Error marking payment as paid',
  },

  reports: {
    title: 'Reports',
    subtitle: 'View and analyze your finances',
    categoryBreakdown: 'Category Breakdown',
    monthlyTrend: 'Monthly Trend',
    yearlyOverview: 'Yearly Overview',
    selectMonth: 'Select month',
    selectYear: 'Select year',
    noDataAvailable: 'No data available for this period',
    paymentMethods: 'Payment Methods',
    transactionCount: 'transactions',
    dailyTrend: 'Daily Trend',
    incomeByCategory: 'Income by Category',
    expensesByCategory: 'Expenses by Category',
    noIncomeData: 'No income for this period',
    noExpenseData: 'No expenses for this period',
  },

  profile: {
    title: 'Profile',
    settings: 'Profile Settings',
    subtitle: 'Manage your profile and WhatsApp bot configuration',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Enter your display name',
    email: 'Email',
    emailCannotChange: 'Email cannot be changed. Contact support if needed.',
    saveChanges: 'Save Changes',
    updateFailed: 'Failed to update profile',
    whatsappNumbers: 'WhatsApp Numbers',
    authorizedGroups: 'Authorized Groups',
    language: 'Language',
  },

  whatsapp: {
    title: 'WhatsApp Configuration',
    subtitle: 'Manage authorized WhatsApp numbers and their permissions',
    addNumber: 'Add Number',
    editNumber: 'Edit WhatsApp Number',
    addNumberTitle: 'Add WhatsApp Number',
    editNumberSubtitle: 'Update the WhatsApp number and its permissions.',
    addNumberSubtitle: 'Add a WhatsApp number that can interact with the bot. Set permissions to control what this number can do.',
    noNumbers: 'No WhatsApp numbers added yet.',
    name: 'Name / Label',
    namePlaceholder: 'e.g., Spouse, John, Me',
    nameHelp: 'A label to identify this number',
    number: 'WhatsApp Number',
    numberPlaceholder: '5511999999999',
    numberHelp: 'Enter the full WhatsApp number including country code (e.g., 5511999999999)',
    isPrimary: 'Set as primary number',
    onlyOnePrimary: 'Only one number can be primary.',
    primary: 'Primary',
    permissions: 'Permissions',
    permissionView: 'View Transactions',
    permissionViewDesc: 'Can view all transactions and balances',
    permissionAdd: 'Add Transactions',
    permissionAddDesc: 'Can add new income and expenses',
    permissionEdit: 'Edit Transactions',
    permissionEditDesc: 'Can modify existing transactions',
    permissionDelete: 'Delete Transactions',
    permissionDeleteDesc: 'Can delete transactions',
    permissionBudgets: 'Manage Budgets',
    permissionBudgetsDesc: 'Can create, edit, and delete budgets',
    permissionReports: 'View Reports',
    permissionReportsDesc: 'Can view financial reports and analytics',
    view: 'View',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    budgets: 'Budgets',
    reports: 'Reports',
    deleteConfirm: 'Are you sure you want to delete this WhatsApp number?',
    deleteFailed: 'Failed to delete WhatsApp number',
    invalidNumber: 'Please enter a valid WhatsApp number',
    saveFailed: 'Failed to save WhatsApp number',
  },

  groups: {
    title: 'Authorized Groups',
    subtitle: 'WhatsApp groups where the bot is authorized to respond to messages',
    noGroups: 'No authorized groups yet.',
    noGroupsHelp: 'Add the bot to a group to see it here. Groups are automatically authorized when added by you.',
    unknownGroup: 'Unknown Group',
    autoAuthorized: 'Auto-authorized',
    active: 'Active',
    inactive: 'Inactive',
    addedBy: 'Added by',
    lastMessage: 'Last message',
    never: 'Never',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    weeksAgo: 'w ago',
    activate: 'Activate',
    deactivate: 'Deactivate',
    deleteConfirm: 'Are you sure you want to remove authorization for',
    updateFailed: 'Failed to update group status',
    deleteFailed: 'Failed to delete authorized group',
  },

  auth: {
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    newPassword: 'New Password',
    passwordRequirement: 'Must be at least 6 characters',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordMismatch: 'Passwords do not match',
    emailRequired: 'Email is required',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signInWithEmail: 'Sign in with Email',
    signUpWithEmail: 'Sign up with Email',
    backToLogin: 'Back to login',
    loginDescription: 'Choose your preferred login method',

    passwordResetError: 'Failed to send reset email. Please try again.',
    magicLinkError: 'Failed to send magic link. Please try again.',

    // Forgot Password (nested structure with label for link)
    forgotPassword: {
      label: 'Forgot password?',
      title: 'Forgot Password?',
      description: "Enter your email and we'll send you a link to reset your password",
      sendLink: 'Send Reset Link',
      info: "You'll receive an email with a secure link to reset your password. The link expires in 1 hour.",
      success: {
        title: 'Check your email!',
        description: "We've sent a password reset link to {email}. Click the link in the email to create a new password.",
        note: "Didn't receive the email? Check your spam folder or try again.",
      },
      sendAnother: 'Send another email',
    },

    // Reset Password (nested structure)
    resetPassword: {
      title: 'Reset Password',
      description: 'Choose a new password for your account',
      button: 'Reset Password',
      invalidToken: 'Invalid or expired reset link. Please request a new one.',
      sessionError: 'Unable to verify reset link. Please try again.',
      error: 'Failed to reset password. Please try again.',
      success: {
        title: 'Password reset successful!',
        description: 'Your password has been updated. Redirecting you to login...',
      },
      invalidTitle: 'Invalid Reset Link',
      linkExpired: 'Password reset links expire after 1 hour for security. Please request a new link.',
      requestNew: 'Request New Link',
    },

    // Magic Link (nested structure with label for tab)
    magicLink: {
      label: 'Magic Link',
      info: "We'll send you a secure login link via email. No password needed!",
      sendLink: 'Send Magic Link',
      success: {
        title: 'Check your email!',
        description: "We've sent a magic link to {email}. Click the link in the email to log in instantly.",
        note: "The link will expire in 1 hour. Didn't receive it? Check your spam folder.",
      },
      sendAnother: 'Send another link',
    },
  },

  settings: {
    account: {
      title: 'Account Settings',
      subtitle: 'Manage your account information and data',
      accountInfo: 'Account Information',
      dataSummary: 'Your Data Summary',
      transactions: 'Transactions',
      categories: 'Categories',
      budgets: 'Budgets',
      recurringPayments: 'Recurring Payments',
      whatsappNumbers: 'WhatsApp Numbers',
      authorizedGroups: 'Authorized Groups',
      dataRights: 'Your Data Rights (LGPD)',
      dataRightsDescription: 'According to Brazilian data protection law (LGPD), you have the right to:',
      rightAccess: 'Access your personal data',
      rightCorrect: 'Correct inaccurate data',
      rightDelete: 'Request deletion of your data',
      rightPortability: 'Data portability',
      dangerZone: 'Danger Zone',
      deleteAccount: 'Delete My Account',
      deleteAccountWarning: 'Permanently delete your account and all associated data. This action cannot be undone.',
      deleteAccountInfo: 'This will permanently delete:',
      deleteAllTransactions: 'All your transactions',
      deleteAllBudgets: 'All budgets and categories',
      deleteWhatsappIntegration: 'WhatsApp integration',
      deleteAiUsageHistory: 'AI usage history',
      accountWillBeInaccessible: 'Your account will be permanently inaccessible',
      confirmDeletion: 'To confirm deletion, type DELETE MY ACCOUNT below:',
      deleteForever: 'Delete Forever',
      deleting: 'Deleting...',
      deletionSuccess: 'Your account has been deleted successfully. Redirecting...',
      deletionFailed: 'Failed to delete account. Please try again.',
      confirmationRequired: 'Please type DELETE MY ACCOUNT to confirm',
    },
    notifications: {
      title: 'Notification Preferences',
      reengagement_label: 'Re-engagement Messages',
      reengagement_description: 'Receive reminders when inactive (goodbye message and weekly review)',
      info_note: 'Note: This preference does not affect onboarding tips you receive when completing tiers.',
      success_toast: 'Preferences saved',
      error_toast: 'Failed to save preferences. Please try again.',
    },
  },

  months: {
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
  },

  table: {
    date: 'Date',
    description: 'Description',
    category: 'Category',
    paymentMethod: 'Payment Method',
    amount: 'Amount',
    type: 'Type',
    actions: 'Actions',
  },

  onboarding: {
    progress: 'Step {current} of {total}',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    skipTour: 'Skip Tour',
    getStarted: 'Get Started',
    complete: 'Complete',

    welcome: {
      title: 'Welcome',
      heading: 'Welcome to NexFinApp!',
      intro: 'Your personal finance assistant via WhatsApp',
      feature1Title: 'Track Expenses Easily',
      feature1Desc: 'Just send a message like "Spent 50 on food"',
      feature2Title: 'Smart OCR',
      feature2Desc: 'Send photos of receipts or bank SMS',
      feature3Title: 'Monthly Budgets',
      feature3Desc: 'Set limits and get alerts',
    },

    whatsapp: {
      title: 'WhatsApp',
      heading: 'Connect Your WhatsApp',
      description: 'Manage finances directly from WhatsApp',
      explanation: 'Add your WhatsApp number to start receiving updates and interact with the bot.',
      instructions: 'Click the button below to add your WhatsApp number',
      addButton: 'Add WhatsApp Number',
      connected: 'WhatsApp Connected!',
    },

    category: {
      title: 'Categories',
      heading: 'Create Your First Category',
      description: 'Organize your expenses',
      explanation: 'Categories help you organize and track different types of expenses.',
      tip: 'Pro Tip:',
      tipDetail: 'Common categories include: Food, Transport, Rent, Entertainment',
      goToCategories: 'Go to Categories',
    },

    expense: {
      tutorialTitle: 'Add Your First Expense',
      tutorialDescription: 'Click here to add a transaction. You can do this via WhatsApp or the web interface.',
    },

    features: {
      title: 'Features',
      heading: 'Powerful Features',
      description: 'What you can do',
      explanation: 'Here are the key features to help you manage your finances:',
      tutorialTitle: 'Explore All Features',
      tutorialDescription: 'Access reports, budgets, categories, and recurring transactions from here. Start exploring!',

      naturalLanguage: {
        title: 'Natural Language',
        description: 'Just talk naturally, no commands needed',
        example: '"Spent 50 on lunch today"',
      },

      ocr: {
        title: 'OCR for Bank SMS',
        description: 'Send photos of bank messages for automatic expense extraction',
        example: 'Just send a photo of your bank SMS!',
      },

      budgets: {
        title: 'Monthly Budgets',
        description: 'Set spending limits and get alerts when you\'re close',
      },
    },
  },

  // Credit Mode Selection
  credit_mode: {
    dialog_title: 'Choose Your Credit Card Mode',
    credit_mode_heading: 'Credit Mode',
    simple_mode_heading: 'Debit Mode',
    credit_benefits: [
      'Track installments (3x, 12x, etc)',
      'Personal monthly budget per card',
      'Statement closing reminders',
      'Ideal for installment purchases',
    ],
    simple_benefits: [
      'Treat credit card like debit',
      'No extra credit features',
      'Simple expense tracking',
      'Ideal for paying in full monthly',
    ],
    whats_difference: 'What\'s the difference?',
    comparison_table: {
      expense_tracking: 'Expense Tracking',
      installments: 'Installments',
      statement_budgets: 'Statement Budgets',
      payment_reminders: 'Payment Reminders',
      simplicity: 'Simplicity',
      both: 'Both',
      yes: 'Yes',
      no: 'No',
      advanced: 'Advanced',
      maximum: 'Maximum',
    },
    choose_credit_button: 'Choose Credit Mode',
    choose_simple_button: 'Choose Debit Mode',
    success_credit: 'Credit Mode enabled!',
    success_simple: 'Debit Mode enabled!',
    error: 'Failed to set mode. Please try again.',

    // Mode Switching (Story 1.5)
    switch_warning_title: '⚠️ Warning: Mode Change',
    switch_warning_message: 'You have {count} active installment(s). What do you want to do?',
    option_keep_installments: 'Keep installments active',
    option_keep_description: 'Future installments continue appearing. You can switch back to Credit Mode later. Installments will not be deleted.',
    option_pay_off: 'Pay off all now',
    option_pay_off_description: 'Marks all as "paid off early". Removes future installments. History of paid installments is preserved.',
    option_cancel: 'Cancel change',
    option_cancel_description: 'Stay in Credit Mode. Nothing is changed.',
    mode_switched_keep: 'Mode changed. Active installments will continue.',
    mode_switched_payoff: 'Mode changed. {count} installments marked as paid off.',
    mode_switched_success: 'Mode changed successfully!',
    simple_switch_confirm: 'Switch to Debit Mode? Credit features will be disabled.',
    credit_switch_confirm: 'Switch to Credit Mode? You\'ll gain access to installments, statement tracking, and credit budgets.',
    switch_button: 'Switch to {mode}',
    switch_to_credit: 'Switch to Credit Mode',
    switch_to_simple: 'Switch to Debit Mode',
    current_mode: 'Current mode: {mode}',
    credit_mode_label: 'Credit Mode',
    simple_mode_label: 'Debit Mode',
    simple_mode_badge: 'Debit Mode',
    simple_mode_description: 'Simple expense tracking, no credit features',
    settings_title: 'Credit Card Settings',
    settings_description: 'Manage your credit card tracking modes',
    no_credit_cards: 'No credit cards found',
    switching: 'Switching...',
    credit_switch_title: 'Enable Credit Mode?',
    credit_switch_description: 'You\'ll gain access to installments, statement tracking, and credit budgets.',
    confirm_switch: 'Confirm',
    cancel_switch: 'Cancel',

    // Add Credit Card Dialog
    add_card: 'Add Card',
    add_card_title: 'Add Credit Card',
    add_card_description: 'Configure your new credit card',
    card_name_label: 'Card name',
    card_name_placeholder: 'E.g., Chase, Amex...',
    select_mode_label: 'Tracking mode',
    credit_mode_option: 'Credit Mode',
    credit_mode_explanation: 'Track statements, installments, budgets and receive payment reminders',
    simple_mode_option: 'Debit Mode',
    simple_mode_explanation: 'Just record expenses without statement tracking',
    statement_settings_section: 'Statement Settings',
    closing_day_label: 'Statement closing day',
    closing_day_select_placeholder: 'Select day',
    due_day_label: 'Days after closing for payment',
    due_day_placeholder: 'E.g., 10',
    create_card: 'Create Card',
    creating_card: 'Creating...',
    card_created_success: 'Card created successfully!',
    card_name_required: 'Card name is required',
    card_name_duplicate: 'A card with this name already exists',
    card_mode_required: 'Select a card mode',
  },

  // Future Commitments Dashboard (Story 2.3)
  futureCommitments: {
    title: 'Future Commitments',
    monthFormat: '{month} {year}',
    paymentCount: '{count} payments',
    paymentCount_one: '{count} payment',
    emptyState: 'You don\'t have any active installments.',
    createButton: 'Create Installment',
    monthlyTotal: 'R$ {amount}',
    installmentProgress: '{current}/{total}',
    viewAll: 'View all',
    loading: 'Loading commitments...',
    error: 'Error loading commitments',
    retry: 'Try again',
  },

  installments: {
    pageTitle: 'My Installments',
    tabs: {
      active: 'Active',
      paidOff: 'Paid Off',
      activeCount: 'Active ({count})',
      paidOffCount: 'Paid Off ({count})',
    },
    card: {
      totalAmount: 'Total: {amount} in {count}x of {monthlyPayment}',
      progress: '{paid}/{total} paid',
      remaining: 'Remaining: {amount}',
      nextPayment: 'Next payment: {date}',
      completedOn: 'Paid off on: {date}',
    },
    actions: {
      viewDetails: 'View Details',
      payOff: 'Pay Off',
      edit: 'Edit',
      delete: 'Delete',
    },
    detailsModal: {
      title: 'Installment Details',
      paymentSchedule: 'Payment Schedule',
      totalPaid: 'Total Paid: {amount} ({count} payments)',
      totalPaid_one: 'Total Paid: {amount} ({count} payment)',
      totalRemaining: 'Total Remaining: {amount} ({count} payments)',
      totalRemaining_one: 'Total Remaining: {amount} ({count} payment)',
      transaction: 'Transaction: #{id} ({date})',
      paymentItem: '{number}/{total} - {amount} - Due: {date}',
      statusPaid: 'PAID',
      statusPending: 'PENDING',
      statusCancelled: 'CANCELLED',
      close: 'Close',
    },
    emptyState: {
      active: 'You don\'t have any active installments.',
      activeDescription: 'Create a new installment to start tracking your installment purchases.',
      paidOff: 'You haven\'t paid off any installments yet.',
      paidOffDescription: 'When you pay off an installment, it will appear here.',
      createButton: 'Create Installment',
    },
    pagination: {
      showing: 'Showing {start}-{end} of {total} installments',
      previous: 'Previous',
      next: 'Next',
      page: 'Page {page}',
    },
    loading: 'Loading installments...',
    error: 'Error loading installments',
    retry: 'Try again',
    payoff: {
      dialogTitle: 'Pay Off Installment?',
      totalOriginal: 'Total Original: {amount} in {count}x',
      alreadyPaid: 'Already Paid: {amount} ({count} payments)',
      alreadyPaid_one: 'Already Paid: {amount} ({count} payment)',
      remaining: 'Remaining Amount: {amount} ({count} payments)',
      remaining_one: 'Remaining Amount: {amount} ({count} payment)',
      whatHappens: 'What will happen:',
      markedAsPaidOff: 'Installment marked as paid off',
      futurePaymentsCancelled: '{count} future payments cancelled',
      futurePaymentsCancelled_one: '{count} future payment cancelled',
      paidPaymentsPreserved: 'Paid payments remain in history',
      commitmentsUpdated: 'Future commitments updated',
      warningIrreversible: 'This action cannot be undone.',
      buttonCancel: 'Cancel',
      buttonConfirm: 'Confirm Pay Off',
      buttonNext: 'Next',
      successTitle: 'Installment paid off!',
      successDetails: '{count} future payments removed.',
      successDetails_one: '{count} future payment removed.',
      successAmount: 'Amount removed: {amount}',
      errorNotFound: 'Installment not found',
      errorUnauthorized: 'You don\'t have permission to pay off this installment',
      errorAlreadyPaidOff: 'Installment already paid off',
      errorCancelled: 'Cancelled installment cannot be paid off',
      errorGeneric: 'Error paying off installment. Please try again.',
      loadingConfirmation: 'Loading...',
      confirmingPayoff: 'Confirming pay off...',

      // Step 2: Transaction Handling
      transactionHandlingTitle: 'Future Transactions',
      transactionHandlingWarning: 'This installment has {count} future transactions that will be deleted.',
      transactionHandlingWarning_one: 'This installment has {count} future transaction that will be deleted.',
      transactionHandlingQuestion: 'What would you like to do?',
      optionJustDelete: 'Just Delete Transactions',
      optionJustDeleteDesc: 'Remove all future transactions. No payment record will be created.',
      optionCreateTransaction: 'Create Payoff Transaction',
      optionCreateTransactionDesc: 'Delete future transactions AND create a debit transaction to record your payoff payment.',
      payoffAmountLabel: 'Payoff Amount',
      payoffAmountPlaceholder: 'E.g., 1200.00',
      paymentMethodLabel: 'Payment Method',
      paymentMethodPlaceholder: 'Select...',
      payoffDateLabel: 'Payoff Date',
      transactionsDeletedCount: '{count} transactions deleted',
      transactionsDeletedCount_one: '{count} transaction deleted',
      payoffTransactionCreated: 'Payoff transaction created: {amount}',
    },
    edit: {
      dialogTitle: 'Edit Installment',
      description: 'Description',
      descriptionPlaceholder: 'E.g.: Samsung Phone',
      category: 'Category',
      categoryPlaceholder: 'Select a category',
      merchant: 'Store/Merchant',
      merchantPlaceholder: 'E.g.: Best Buy',
      totalAmount: 'Total Amount',
      totalInstallments: 'Number of Installments',
      monthlyPayment: 'Monthly Payment (recalculated)',
      minInstallments: 'Minimum: {count} (already paid) • Maximum: 60',
      whatHappens: 'What will happen:',
      paidUnchanged: '{count} paid payments remain unchanged',
      paidUnchanged_one: '{count} paid payment remains unchanged',
      pendingRecalculated: '{count} pending payments will be recalculated',
      pendingRecalculated_one: '{count} pending payment will be recalculated',
      paymentsAdded: '{count} payments added',
      paymentsAdded_one: '{count} payment added',
      paymentsRemoved: '{count} payments removed',
      paymentsRemoved_one: '{count} payment removed',
      monthlyChange: 'Monthly payment: {oldAmount} → {newAmount}',
      commitmentsUpdated: 'Future commitments updated',
      buttonCancel: 'Cancel',
      buttonSave: 'Save Changes',
      successTitle: 'Installment updated!',
      successFields: 'Fields updated: {fields}',
      errorDescriptionRequired: 'Description is required',
      errorAmountInvalid: 'Amount must be greater than zero',
      errorInstallmentsTooLow: 'Number of installments cannot be less than {count} (already paid)',
      errorInstallmentsTooHigh: 'Maximum of 60 installments allowed',
      errorNotFound: 'Installment not found',
      errorUnauthorized: 'You don\'t have permission to edit this installment',
      errorGeneric: 'Error editing installment. Please try again.',
      errorNoChanges: 'No changes detected',
      errorCannotEditPaidOff: 'Cannot edit paid off installment',
      errorCannotEditCancelled: 'Cannot edit cancelled installment',
      warningUnsavedChanges: 'You have unsaved changes. Discard?',
      loading: 'Loading...',
      saving: 'Saving changes...',
    },
    delete: {
      dialogTitle: 'Delete Installment?',
      warningIntro: 'You are about to permanently delete:',
      currentStatus: 'Current status:',
      paidPayments: '{count} paid payments ({amount})',
      paidPayments_one: '{count} paid payment ({amount})',
      pendingPayments: '{count} pending payments ({amount})',
      pendingPayments_one: '{count} pending payment ({amount})',
      whatHappens: '⚠️ What will happen:',
      planRemoved: 'The plan will be permanently removed',
      pendingDeleted: '{count} pending payments will be deleted',
      pendingDeleted_one: '{count} pending payment will be deleted',
      paidPreserved: '{count} paid transactions remain (unlinked)',
      paidPreserved_one: '{count} paid transaction remains (unlinked)',
      commitmentsUpdated: '{amount} removed from future commitments',
      irreversible: 'This action cannot be undone',
      confirmPrompt: 'Are you sure you want to delete?',
      buttonCancel: 'Cancel',
      buttonDelete: 'Delete Permanently',
      successTitle: 'Installment deleted',
      successDescription: '{description} permanently removed.',
      successPendingDeleted: '{count} pending payments deleted',
      successPendingDeleted_one: '{count} pending payment deleted',
      successPaidPreserved: '{count} paid transactions preserved',
      successPaidPreserved_one: '{count} paid transaction preserved',
      successCommitmentsUpdated: 'Future commitments updated',
      errorNotFound: 'Installment not found',
      errorUnauthorized: 'You don\'t have permission to delete this installment',
      errorGeneric: 'Error deleting installment. Please try again.',
      loading: 'Loading...',
      deleting: 'Deleting installment...',
    },
    markAsPaid: {
      button: 'Mark as Paid',
      marking: 'Marking...',
      successTitle: 'Payment marked as paid!',
      successDescription: 'The payment was successfully marked as paid.',
      errorTitle: 'Error marking payment',
      errorDescription: 'Could not mark the payment as paid. Please try again.',
    },
  },

  statementPeriod: {
    currentBadge: 'Current statement',
    nextBadge: 'Next statement',
    pastBadge: 'Past statement',
    currentBadgeShort: 'Current',
    nextBadgeShort: 'Next',
    pastBadgeShort: 'Past',
    periodContext: '{period} statement ({start} - {end})',
    currentPeriod: 'Current',
    nextPeriod: 'Next',
    pastPeriod: 'Past',
  },
}

export const formatHelpers: FormatHelpers = {
  formatCurrency: (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(value)
  },

  formatDate: (date: Date | string) => {
    const dateObj = typeof date === 'string' ? new Date(date) : date
    return new Intl.DateTimeFormat('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
    }).format(dateObj)
  },

  formatNumber: (value: number) => {
    return new Intl.NumberFormat('en-US').format(value)
  },

  getMonthName: (month: number) => {
    const monthNames = [
      messages.months.january,
      messages.months.february,
      messages.months.march,
      messages.months.april,
      messages.months.may,
      messages.months.june,
      messages.months.july,
      messages.months.august,
      messages.months.september,
      messages.months.october,
      messages.months.november,
      messages.months.december,
    ]
    return monthNames[month - 1] || ''
  },

  getCurrencySymbol: () => '$',
}
