import type { Messages, FormatHelpers } from './types'

export const messages: Messages = {
  common: {
    cancel: 'Cancelar',
    save: 'Salvar',
    add: 'Adicionar',
    edit: 'Editar',
    delete: 'Excluir',
    update: 'Atualizar',
    loading: 'Carregando...',
    saving: 'Salvando...',
    deleting: 'Excluindo...',
    select: 'Selecionar',
    optional: 'Opcional',
    required: 'Obrigatório',
    all: 'Todos',
    custom: 'Personalizado',
    day: 'Dia',
    confirmDelete: 'Tem certeza que deseja excluir?',
  },

  nav: {
    home: 'Início',
    reports: 'Relatórios',
    budgets: 'Orçamentos',
    categories: 'Categorias',
    recurring: 'Recorrentes',
    profile: 'Perfil',
    signOut: 'Sair',
  },

  home: {
    title: 'Controle de Despesas',
    subtitle: 'Gerencie suas finanças com facilidade',
    addTransaction: 'Adicionar Transação',
  },

  balance: {
    totalBalance: 'Saldo Total',
    currentBalance: 'Saldo atual',
    income: 'Receitas',
    totalIncome: 'Total de receitas',
    expenses: 'Despesas',
    totalExpenses: 'Total de despesas',
  },

  transaction: {
    title: 'Transação',
    transactions: 'Transações',
    addTitle: 'Adicionar Transação',
    editTitle: 'Editar Transação',
    addDescription: 'Adicione uma nova transação de receita ou despesa.',
    editDescription: 'Atualize os detalhes da sua transação.',
    type: 'Tipo',
    amount: 'Valor',
    category: 'Categoria',
    date: 'Data',
    paymentMethod: 'Método de Pagamento',
    description: 'Descrição',
    selectCategory: 'Selecione uma categoria',
    selectPaymentMethod: 'Selecione o método de pagamento',
    optionalDescription: 'Descrição opcional...',
    income: 'Receita',
    expense: 'Despesa',
    noTransactions: 'Nenhuma transação encontrada',
    addFirstTransaction: 'Adicione sua primeira transação',
    allTypes: 'Todos os Tipos',
    allCategories: 'Todas as Categorias',
    deleteConfirm: 'Tem certeza que deseja excluir esta transação?',
  },

  paymentMethods: {
    cash: 'Dinheiro',
    creditCard: 'Cartão de Crédito',
    debitCard: 'Cartão de Débito',
    bankTransfer: 'Transferência Bancária',
    pix: 'PIX',
    other: 'Outro',
  },

  budget: {
    title: 'Orçamento',
    addTitle: 'Adicionar Orçamento',
    editTitle: 'Editar Orçamento',
    addDescription: 'Defina um orçamento para uma categoria.',
    editDescription: 'Atualize seu orçamento.',
    spent: 'Gasto',
    remaining: 'Restante',
    overBudget: 'Acima do orçamento',
    nearLimit: 'Perto do limite',
    onTrack: 'No caminho certo',
    noBudgets: 'Nenhum orçamento encontrado',
    addFirstBudget: 'Adicione seu primeiro orçamento',
    month: 'Mês',
    year: 'Ano',
    amount: 'Valor',
    subtitle: 'Acompanhe seus limites de gastos para',
  },

  category: {
    title: 'Categoria',
    categories: 'Categorias',
    addTitle: 'Adicionar Categoria',
    editTitle: 'Editar Categoria',
    deleteTitle: 'Excluir Categoria',
    deleteConfirm: 'Tem certeza que deseja excluir a categoria',
    name: 'Nome',
    type: 'Tipo',
    icon: 'Ícone',
    color: 'Cor',
    noCategories: 'Nenhuma categoria encontrada',
    addFirstCategory: 'Adicione sua primeira categoria',
    subtitle: 'Gerencie suas categorias de despesas e receitas',
    income: 'Categorias de Receita',
    incomeDescription: 'Categorias para rastrear suas receitas',
    expense: 'Categorias de Despesa',
    expenseDescription: 'Categorias para rastrear suas despesas',
    noIncome: 'Nenhuma categoria de receita ainda',
    noExpense: 'Nenhuma categoria de despesa ainda',
    cannotDelete: 'Não é possível excluir categorias padrão',
  },

  categories: {
    salary: 'Salário',
    freelance: 'Freelance',
    investments: 'Investimentos',
    other: 'Outro',
    food: 'Alimentação',
    transport: 'Transporte',
    housing: 'Moradia',
    utilities: 'Contas',
    entertainment: 'Entretenimento',
    healthcare: 'Saúde',
    education: 'Educação',
    shopping: 'Compras',
  },

  recurring: {
    title: 'Recorrente',
    addTitle: 'Adicionar Recorrente',
    editTitle: 'Editar Recorrente',
    dayOfMonth: 'Dia do Mês',
    isActive: 'Ativo',
    active: 'Ativo',
    inactive: 'Inativo',
    noRecurring: 'Nenhuma transação recorrente encontrada',
    addFirstRecurring: 'Adicione sua primeira transação recorrente',
    upcomingPayments: 'Próximos Pagamentos',
    markAsPaid: 'Marcar como Pago',
    dueDate: 'Data de Vencimento',
    subtitle: 'Gerencie suas despesas e receitas mensais recorrentes',
    upcomingDescription: 'Marque os pagamentos como pagos quando concluídos',
    templatesDescription: 'Gerencie seus modelos de transações recorrentes',
  },

  reports: {
    title: 'Relatórios',
    subtitle: 'Visualize e analise suas finanças',
    categoryBreakdown: 'Distribuição por Categoria',
    monthlyTrend: 'Tendência Mensal',
    yearlyOverview: 'Visão Anual',
    selectMonth: 'Selecione o mês',
    selectYear: 'Selecione o ano',
  },

  profile: {
    title: 'Perfil',
    settings: 'Configurações do Perfil',
    subtitle: 'Gerencie seu perfil e configuração do bot do WhatsApp',
    displayName: 'Nome de Exibição',
    displayNamePlaceholder: 'Digite seu nome de exibição',
    email: 'E-mail',
    emailCannotChange: 'O e-mail não pode ser alterado. Entre em contato com o suporte se necessário.',
    saveChanges: 'Salvar Alterações',
    updateFailed: 'Falha ao atualizar perfil',
    whatsappNumbers: 'Números do WhatsApp',
    authorizedGroups: 'Grupos Autorizados',
    language: 'Idioma',
  },

  whatsapp: {
    title: 'Configuração do WhatsApp',
    subtitle: 'Gerencie números de WhatsApp autorizados e suas permissões',
    addNumber: 'Adicionar Número',
    editNumber: 'Editar Número do WhatsApp',
    addNumberTitle: 'Adicionar Número do WhatsApp',
    editNumberSubtitle: 'Atualize o número do WhatsApp e suas permissões.',
    addNumberSubtitle: 'Adicione um número do WhatsApp que pode interagir com o bot. Defina permissões para controlar o que este número pode fazer.',
    noNumbers: 'Nenhum número do WhatsApp adicionado ainda.',
    name: 'Nome / Identificação',
    namePlaceholder: 'ex: Esposo(a), João, Eu',
    nameHelp: 'Uma identificação para este número',
    number: 'Número do WhatsApp',
    numberPlaceholder: '5511999999999',
    numberHelp: 'Digite o número completo do WhatsApp incluindo código do país (ex: 5511999999999)',
    isPrimary: 'Definir como número principal',
    onlyOnePrimary: 'Apenas um número pode ser principal.',
    primary: 'Principal',
    permissions: 'Permissões',
    permissionView: 'Visualizar Transações',
    permissionViewDesc: 'Pode visualizar todas as transações e saldos',
    permissionAdd: 'Adicionar Transações',
    permissionAddDesc: 'Pode adicionar novas receitas e despesas',
    permissionEdit: 'Editar Transações',
    permissionEditDesc: 'Pode modificar transações existentes',
    permissionDelete: 'Excluir Transações',
    permissionDeleteDesc: 'Pode excluir transações',
    permissionBudgets: 'Gerenciar Orçamentos',
    permissionBudgetsDesc: 'Pode criar, editar e excluir orçamentos',
    permissionReports: 'Visualizar Relatórios',
    permissionReportsDesc: 'Pode visualizar relatórios financeiros e análises',
    view: 'Visualizar',
    add: 'Adicionar',
    edit: 'Editar',
    delete: 'Excluir',
    budgets: 'Orçamentos',
    reports: 'Relatórios',
    deleteConfirm: 'Tem certeza que deseja excluir este número do WhatsApp?',
    deleteFailed: 'Falha ao excluir número do WhatsApp',
    invalidNumber: 'Por favor, digite um número de WhatsApp válido',
    saveFailed: 'Falha ao salvar número do WhatsApp',
  },

  groups: {
    title: 'Grupos Autorizados',
    subtitle: 'Grupos do WhatsApp onde o bot está autorizado a responder mensagens',
    noGroups: 'Nenhum grupo autorizado ainda.',
    noGroupsHelp: 'Adicione o bot a um grupo para vê-lo aqui. Os grupos são autorizados automaticamente quando adicionados por você.',
    unknownGroup: 'Grupo Desconhecido',
    autoAuthorized: 'Auto-autorizado',
    active: 'Ativo',
    inactive: 'Inativo',
    addedBy: 'Adicionado por',
    lastMessage: 'Última mensagem',
    never: 'Nunca',
    justNow: 'Agora mesmo',
    minutesAgo: 'm atrás',
    hoursAgo: 'h atrás',
    daysAgo: 'd atrás',
    weeksAgo: 's atrás',
    activate: 'Ativar',
    deactivate: 'Desativar',
    deleteConfirm: 'Tem certeza que deseja remover a autorização para',
    updateFailed: 'Falha ao atualizar status do grupo',
    deleteFailed: 'Falha ao excluir grupo autorizado',
  },

  auth: {
    login: 'Entrar',
    signup: 'Criar Conta',
    email: 'E-mail',
    password: 'Senha',
    confirmPassword: 'Confirmar Senha',
    forgotPassword: 'Esqueceu a senha?',
    noAccount: 'Não tem uma conta?',
    haveAccount: 'Já tem uma conta?',
    signInWithEmail: 'Entrar com E-mail',
    signUpWithEmail: 'Criar Conta com E-mail',
  },

  months: {
    january: 'Janeiro',
    february: 'Fevereiro',
    march: 'Março',
    april: 'Abril',
    may: 'Maio',
    june: 'Junho',
    july: 'Julho',
    august: 'Agosto',
    september: 'Setembro',
    october: 'Outubro',
    november: 'Novembro',
    december: 'Dezembro',
  },

  table: {
    date: 'Data',
    description: 'Descrição',
    category: 'Categoria',
    paymentMethod: 'Método de Pagamento',
    amount: 'Valor',
    type: 'Tipo',
    actions: 'Ações',
  },
}

export const formatHelpers: FormatHelpers = {
  formatCurrency: (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL',
    }).format(value)
  },

  formatDate: (date: Date | string) => {
    const dateObj = typeof date === 'string' ? new Date(date) : date
    return new Intl.DateTimeFormat('pt-BR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
    }).format(dateObj)
  },

  formatNumber: (value: number) => {
    return new Intl.NumberFormat('pt-BR').format(value)
  },

  getMonthName: (month: number) => {
    const monthNames = [
      messages.months.january,
      messages.months.february,
      messages.months.march,
      messages.months.april,
      messages.months.may,
      messages.months.june,
      messages.months.july,
      messages.months.august,
      messages.months.september,
      messages.months.october,
      messages.months.november,
      messages.months.december,
    ]
    return monthNames[month - 1] || ''
  },

  getCurrencySymbol: () => 'R$',
}
