export type Locale = 'pt-br' | 'en'

export interface Messages {
  // Allow additional sections for extensibility
  [key: string]: any

  // Common
  common: {
    cancel: string
    save: string
    add: string
    edit: string
    delete: string
    update: string
    loading: string
    saving: string
    deleting: string
    sending: string
    updating: string
    select: string
    optional: string
    required: string
    all: string
    custom: string
    day: string
    days: string
    current: string
    confirmDelete: string
    locale: string
    uncategorized: string
  }

  // Navigation
  nav: {
    home: string
    reports: string
    budgets: string
    categories: string
    recurring: string
    profile: string
    signOut: string
    // New grouped navigation
    overview: string
    dashboard: string
    creditCards: string
    installments: string
    manageCreditCards: string
    settings: string
    paymentMethods: string
  }

  // Home page
  home: {
    title: string
    subtitle: string
    addTransaction: string
  }

  // Balance card
  balance: {
    totalBalance: string
    currentBalance: string
    income: string
    totalIncome: string
    expenses: string
    totalExpenses: string
  }

  // Transaction
  transaction: {
    title: string
    transactions: string
    addTitle: string
    editTitle: string
    addDescription: string
    editDescription: string
    type: string
    amount: string
    category: string
    date: string
    paymentMethod: string
    description: string
    selectCategory: string
    selectPaymentMethod: string
    suggestedPaymentMethods: string
    willBeCreated: string
    paymentMethodError: string
    optionalDescription: string
    income: string
    expense: string
    noTransactions: string
    addFirstTransaction: string
    allTypes: string
    allCategories: string
    deleteConfirm: string
    deleteAutoGeneratedTitle: string
    deleteAutoGeneratedMessage: string
    deleteAutoGeneratedCancel: string
    deleteAutoGeneratedConfirm: string
    autoPaymentEdited: string
    autoPaymentDeleted: string
    autoGenerated: string
    installments: string
    installmentsDescription: string
    installment: {
      toggleLabel: string
      totalAmountLabel: string
      totalAmountPlaceholder: string
      installmentsLabel: string
      monthlyPaymentLabel: string
      monthlyPaymentFormat: string
      firstPaymentLabel: string
      lastPaymentNote: string
      createSuccess: string
      createSuccessDetails: string
      createError: string
      validationAmountPositive: string
      validationAmountRequired: string
      validationInstallmentsMin: string
      validationInstallmentsMax: string
      validationDateRequired: string
      validationPastDateWarning: string
      validationSimpleModeError: string
      merchantLabel: string
      merchantPlaceholder: string
    }
  }

  // Payment method types (for dropdowns/selects)
  paymentMethodTypes: {
    cash: string
    creditCard: string
    debitCard: string
    bankTransfer: string
    pix: string
    other: string
    creditMode: string
    simpleMode: string
  }

  // Payment methods page
  paymentMethods: {
    title: string
    subtitle: string
    addMethod: string
    editMethod: string
    deleteMethod: string
    deleteConfirm: string
    deleteWarning: string
    noMethods: string
    noMethodsHint: string
    addFirstMethod: string
    methodName: string
    methodNamePlaceholder: string
    methodNameRequired: string
    methodType: string
    selectType: string
    types: {
      cash: string
      pix: string
      other: string
      credit: string
      debit: string
    }
    helpTitle: string
    helpDescription: string
    addMethodDescription: string
    editMethodDescription: string
    addSuccess: string
    addError: string
    editComingSoon: string
    editError: string
    deleteSuccess: string
    deleteError: string
    createdOn: string
  }

  // Statement settings (Story 3.1)
  statementSettings: {
    title: string
    closingDayLabel: string
    closingDayPlaceholder: string
    notSet: string
    currentPeriod: string
    nextClosing: string
    saveButton: string
    successToast: string
    errorToast: string
    validationError: string
    description: string
    helpText: string
  }

  // Budget settings (Story 3.2)
  budgetSettings: {
    title: string
    label: string
    placeholder: string
    notSet: string
    helperText: string
    saveButton: string
    removeButton: string
    successToast: string
    removedToast: string
    errorToast: string
    validationErrorNegative: string
    validationErrorInvalid: string
    confirmZeroBudget: string
    confirmHighBudget: string
    infoOverBudget: string
    setClosingDateFirst: string
    tooltipTitle: string
    tooltipContent: string
    description: string
  }

  // Payment due settings (Story 4.1)
  paymentDueSettings: {
    title: string
    dueAfterClosingLabel: string
    dueAfterClosingPlaceholder: string
    notSet: string
    previewDueDay: string
    nextPayment: string
    saveButton: string
    successToast: string
    errorToast: string
    validationError: string
    closingDayRequired: string
    setClosingDayButton: string
    description: string
    helpText: string
  }

  // Budget
  budget: {
    title: string
    addTitle: string
    editTitle: string
    addDescription: string
    editDescription: string
    spent: string
    remaining: string
    overBudget: string
    nearLimit: string
    onTrack: string
    noBudgets: string
    addFirstBudget: string
    month: string
    year: string
    amount: string
    subtitle: string
    addGoalTitle: string
    addGoalDescription: string
    budgetLimit: string
    selectCategory: string
    // Story 2.8: Budget with Installments
    statementPeriod: string
    totalSpent: string
    breakdown: string
    categoryTotal: string
    installmentPayment: string
    regularTransaction: string
    uncategorized: string
    noExpenses: string
    performanceNote: string
  }

  // Category
  category: {
    title: string
    categories: string
    addTitle: string
    editTitle: string
    deleteTitle: string
    deleteConfirm: string
    name: string
    type: string
    icon: string
    color: string
    noCategories: string
    addFirstCategory: string
    subtitle: string
    income: string
    incomeDescription: string
    expense: string
    expenseDescription: string
    noIncome: string
    noExpense: string
    cannotDelete: string
    addDescription: string
    editDescription: string
    namePlaceholder: string
    selectType: string
    iconLabel: string
    iconPlaceholder: string
    iconHelp: string
    create: string
    systemBadge: string
    cannotDeleteSystemCategory: string
    deleteSystemCategoryTooltip: string
  }

  // Default categories
  categories: {
    salary: string
    freelance: string
    investments: string
    other: string
    food: string
    transport: string
    housing: string
    utilities: string
    entertainment: string
    healthcare: string
    education: string
    shopping: string
  }

  // Recurring
  recurring: {
    title: string
    addTitle: string
    editTitle: string
    dayOfMonth: string
    isActive: string
    active: string
    inactive: string
    noRecurring: string
    addFirstRecurring: string
    upcomingPayments: string
    for: string
    markAsPaid: string
    dueDate: string
    subtitle: string
    upcomingDescription: string
    templatesDescription: string
    addTransactionTitle: string
    editTransactionTitle: string
    addTransactionDescription: string
    editTransactionDescription: string
    amount: string
    day: string
    descriptionPlaceholder: string
    selectPaymentMethod: string
    viewAll: string
    overdue: string
    overdueLabel: string
    upcoming: string
    overduePayments: string
    upcomingThisMonth: string
    dueToday: string
    dueTomorrow: string
    daysOverdue: string
    daysUntilDue: string
    andXMore: string
    paymentMarkedAsPaid: string
    errorMarkingPayment: string
    markPaid: string
  }

  // Reports
  reports: {
    title: string
    subtitle: string
    categoryBreakdown: string
    monthlyTrend: string
    yearlyOverview: string
    selectMonth: string
    selectYear: string
    noDataAvailable: string
    paymentMethods: string
    transactionCount: string
    dailyTrend: string
    incomeByCategory: string
    expensesByCategory: string
    noIncomeData: string
    noExpenseData: string
  }

  // Profile
  profile: {
    title: string
    settings: string
    subtitle: string
    displayName: string
    displayNamePlaceholder: string
    email: string
    emailCannotChange: string
    saveChanges: string
    updateFailed: string
    whatsappNumbers: string
    authorizedGroups: string
    language: string
  }

  // WhatsApp
  whatsapp: {
    title: string
    subtitle: string
    addNumber: string
    editNumber: string
    addNumberTitle: string
    editNumberSubtitle: string
    addNumberSubtitle: string
    noNumbers: string
    name: string
    namePlaceholder: string
    nameHelp: string
    number: string
    numberPlaceholder: string
    numberHelp: string
    isPrimary: string
    onlyOnePrimary: string
    primary: string
    permissions: string
    permissionView: string
    permissionViewDesc: string
    permissionAdd: string
    permissionAddDesc: string
    permissionEdit: string
    permissionEditDesc: string
    permissionDelete: string
    permissionDeleteDesc: string
    permissionBudgets: string
    permissionBudgetsDesc: string
    permissionReports: string
    permissionReportsDesc: string
    view: string
    add: string
    edit: string
    delete: string
    budgets: string
    reports: string
    deleteConfirm: string
    deleteFailed: string
    invalidNumber: string
    saveFailed: string
  }

  // Groups
  groups: {
    title: string
    subtitle: string
    noGroups: string
    noGroupsHelp: string
    unknownGroup: string
    autoAuthorized: string
    active: string
    inactive: string
    addedBy: string
    lastMessage: string
    never: string
    justNow: string
    minutesAgo: string
    hoursAgo: string
    daysAgo: string
    weeksAgo: string
    activate: string
    deactivate: string
    deleteConfirm: string
    updateFailed: string
    deleteFailed: string
  }

  // Auth
  auth: {
    login: string
    signup: string
    email: string
    password: string
    confirmPassword: string
    noAccount: string
    haveAccount: string
    signInWithEmail: string
    signUpWithEmail: string
    forgotPassword: {
      label: string
      title: string
      description: string
      sendLink: string
      info: string
      success: {
        title: string
        description: string
        note: string
      }
      sendAnother: string
    }
    resetPassword: {
      title: string
      description: string
      button: string
      invalidToken: string
      sessionError: string
      error: string
      success: {
        title: string
        description: string
      }
      invalidTitle: string
      linkExpired: string
      requestNew: string
    }
    [key: string]: any  // Allow any additional auth-related properties
  }

  // Months
  months: {
    january: string
    february: string
    march: string
    april: string
    may: string
    june: string
    july: string
    august: string
    september: string
    october: string
    november: string
    december: string
  }

  // Table
  table: {
    date: string
    description: string
    category: string
    paymentMethod: string
    amount: string
    type: string
    actions: string
  }

  // Onboarding
  onboarding: {
    progress: string
    back: string
    next: string
    skip: string
    skipTour: string
    getStarted: string
    complete: string

    welcome: string | {
      title: string
      heading: string
      intro: string
      feature1Title: string
      feature1Desc: string
      feature2Title: string
      feature2Desc: string
      feature3Title: string
      feature3Desc: string
    }

    whatsapp: {
      title: string
      heading: string
      description: string
      explanation: string
      instructions: string
      addButton: string
      connected: string
    }

    category: {
      title: string
      heading: string
      description: string
      explanation: string
      tip: string
      tipDetail: string
      goToCategories: string
    }

    expense: {
      tutorialTitle: string
      tutorialDescription: string
    }

    features: {
      title: string
      heading: string
      description: string
      explanation: string
      tutorialTitle: string
      tutorialDescription: string

      naturalLanguage: {
        title: string
        description: string
        example: string
      }

      ocr: {
        title: string
        description: string
        example: string
      }

      budgets: {
        title: string
        description: string
      }
    }
    [key: string]: any  // Allow additional onboarding keys for different flows
  }

  // Future Commitments (Story 2.3)
  futureCommitments: {
    title: string
    monthFormat: string
    paymentCount: string
    paymentCount_one: string
    emptyState: string
    createButton: string
    monthlyTotal: string
    installmentProgress: string
    viewAll: string
    loading: string
    error: string
    retry: string
  }

  installments: {
    pageTitle: string
    tabs: {
      active: string
      paidOff: string
      activeCount: string
      paidOffCount: string
    }
    card: {
      totalAmount: string
      progress: string
      remaining: string
      nextPayment: string
      completedOn: string
    }
    actions: {
      viewDetails: string
      payOff: string
      edit: string
      delete: string
    }
    detailsModal: {
      title: string
      paymentSchedule: string
      totalPaid: string
      totalPaid_one: string
      totalRemaining: string
      totalRemaining_one: string
      transaction: string
      paymentItem: string
      statusPaid: string
      statusPending: string
      statusCancelled: string
      close: string
    }
    emptyState: {
      active: string
      activeDescription: string
      paidOff: string
      paidOffDescription: string
      createButton: string
    }
    pagination: {
      showing: string
      previous: string
      next: string
      page: string
    }
    loading: string
    error: string
    retry: string
    payoff: {
      dialogTitle: string
      totalOriginal: string
      alreadyPaid: string
      alreadyPaid_one: string
      remaining: string
      remaining_one: string
      whatHappens: string
      markedAsPaidOff: string
      futurePaymentsCancelled: string
      futurePaymentsCancelled_one: string
      paidPaymentsPreserved: string
      commitmentsUpdated: string
      warningIrreversible: string
      buttonCancel: string
      buttonConfirm: string
      buttonNext: string
      successTitle: string
      successDetails: string
      successDetails_one: string
      successAmount: string
      errorNotFound: string
      errorUnauthorized: string
      errorAlreadyPaidOff: string
      errorCancelled: string
      errorGeneric: string
      loadingConfirmation: string
      confirmingPayoff: string
      // Step 2: Transaction Handling
      transactionHandlingTitle: string
      transactionHandlingWarning: string
      transactionHandlingWarning_one: string
      transactionHandlingQuestion: string
      optionJustDelete: string
      optionJustDeleteDesc: string
      optionCreateTransaction: string
      optionCreateTransactionDesc: string
      payoffAmountLabel: string
      payoffAmountPlaceholder: string
      paymentMethodLabel: string
      paymentMethodPlaceholder: string
      payoffDateLabel: string
      transactionsDeletedCount: string
      transactionsDeletedCount_one: string
      payoffTransactionCreated: string
    }
    edit: {
      dialogTitle: string
      description: string
      descriptionPlaceholder: string
      category: string
      categoryPlaceholder: string
      merchant: string
      merchantPlaceholder: string
      totalAmount: string
      totalInstallments: string
      monthlyPayment: string
      minInstallments: string
      whatHappens: string
      paidUnchanged: string
      paidUnchanged_one: string
      pendingRecalculated: string
      pendingRecalculated_one: string
      paymentsAdded: string
      paymentsAdded_one: string
      paymentsRemoved: string
      paymentsRemoved_one: string
      monthlyChange: string
      commitmentsUpdated: string
      buttonCancel: string
      buttonSave: string
      successTitle: string
      successFields: string
      errorDescriptionRequired: string
      errorAmountInvalid: string
      errorInstallmentsTooLow: string
      errorInstallmentsTooHigh: string
      errorNotFound: string
      errorUnauthorized: string
      errorGeneric: string
      errorNoChanges: string
      errorCannotEditPaidOff: string
      errorCannotEditCancelled: string
      warningUnsavedChanges: string
      loading: string
      saving: string
    }
    delete: {
      dialogTitle: string
      warningIntro: string
      currentStatus: string
      paidPayments: string
      paidPayments_one: string
      pendingPayments: string
      pendingPayments_one: string
      whatHappens: string
      planRemoved: string
      pendingDeleted: string
      pendingDeleted_one: string
      paidPreserved: string
      paidPreserved_one: string
      commitmentsUpdated: string
      irreversible: string
      confirmPrompt: string
      buttonCancel: string
      buttonDelete: string
      successTitle: string
      successDescription: string
      successPendingDeleted: string
      successPendingDeleted_one: string
      successPaidPreserved: string
      successPaidPreserved_one: string
      successCommitmentsUpdated: string
      errorNotFound: string
      errorUnauthorized: string
      errorGeneric: string
      loading: string
      deleting: string
    }
    markAsPaid: {
      button: string
      marking: string
      successTitle: string
      successDescription: string
      errorTitle: string
      errorDescription: string
    }
  }
}

export interface FormatHelpers {
  formatCurrency: (value: number) => string
  formatDate: (date: Date | string) => string
  formatNumber: (value: number) => string
  getMonthName: (month: number) => string
  getCurrencySymbol: () => string
}
