"use client"

import { useState, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { Category, Transaction, PaymentMethod } from "@/lib/types"
import { format, parseISO } from "date-fns"
import { EditIcon, SearchIcon, TrashIcon } from "lucide-react"
import { TransactionDialog } from "./transaction-dialog"
import { deleteTransaction } from "@/lib/actions/transactions"
import { useRouter } from "next/navigation"
import { useTranslations, useLocale } from 'next-intl'
import { formatCurrency } from '@/lib/localization/format'
import { translateCategoryName } from '@/lib/localization/category-translations'
import { getBadgesForTransactions } from '@/lib/utils/statement-period'
import type { TransactionWithPaymentMethod } from '@/lib/utils/statement-period'
import { StatementBadge } from './statement/statement-badge'
import { Badge } from '@/components/ui/badge'

interface TransactionListProps {
  transactions: Transaction[]
  categories: Category[]
  paymentMethods: PaymentMethod[]
}

export function TransactionList({ transactions, categories, paymentMethods }: TransactionListProps) {
  const t = useTranslations()
  const locale = useLocale()
  const router = useRouter()
  const [search, setSearch] = useState("")
  const [typeFilter, setTypeFilter] = useState<string>("all")
  const [categoryFilter, setCategoryFilter] = useState<string>("all")

  const filteredTransactions = transactions.filter((transaction) => {
    const matchesSearch = transaction.description?.toLowerCase().includes(search.toLowerCase()) ?? true
    const matchesType = typeFilter === "all" || transaction.type === typeFilter
    const matchesCategory = categoryFilter === "all" || transaction.category_id === categoryFilter
    return matchesSearch && matchesType && matchesCategory
  })

  // Calculate statement period badges for all transactions (batch calculation)
  // Performance: < 100ms for 50 transactions (Epic3-P4)
  const badgeMap = useMemo(() => {
    // Map transactions to include payment method info
    const transactionsWithPM: TransactionWithPaymentMethod[] = filteredTransactions.map((transaction) => {
      const paymentMethod = paymentMethods.find(pm => pm.id === transaction.payment_method_id)
      return {
        id: transaction.id,
        date: parseISO(transaction.date),
        payment_method_id: transaction.payment_method_id,
        payment_method: paymentMethod ? {
          credit_mode: paymentMethod.credit_mode ?? false,
          statement_closing_day: paymentMethod.statement_closing_day ?? null,
        } : undefined,
      }
    })

    return getBadgesForTransactions(transactionsWithPM)
  }, [filteredTransactions, paymentMethods])

  const handleDelete = async (transaction: Transaction) => {
    // Story 4.4 (AC4.4.2): Custom confirmation for auto-generated transactions
    const confirmationMessage = transaction.metadata?.auto_generated
      ? t('transaction.deleteAutoGeneratedMessage')
      : t('transaction.deleteConfirm')

    if (confirm(confirmationMessage)) {
      try {
        await deleteTransaction(transaction.id)
        router.refresh()
        // Note: Toast notification would be ideal here, but we're using browser confirm()
        // for simplicity. A proper AlertDialog component would provide better UX.
      } catch (error) {
        console.error("Error deleting transaction:", error)
        alert("Error deleting transaction. Please try again.")
      }
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t('transaction.transactions')}</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col gap-4 mb-4 md:flex-row">
          <div className="relative flex-1">
            <SearchIcon className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder={`${t('transaction.title')}...`}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
            />
          </div>

          <Select value={typeFilter} onValueChange={setTypeFilter}>
            <SelectTrigger className="w-full md:w-[180px]">
              <SelectValue placeholder={t('transaction.type')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('transaction.allTypes')}</SelectItem>
              <SelectItem value="income">{t('transaction.income')}</SelectItem>
              <SelectItem value="expense">{t('transaction.expense')}</SelectItem>
            </SelectContent>
          </Select>

          <Select value={categoryFilter} onValueChange={setCategoryFilter}>
            <SelectTrigger className="w-full md:w-[200px]">
              <SelectValue placeholder={t('transaction.category')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('transaction.allCategories')}</SelectItem>
              {categories.map((category) => (
                <SelectItem key={category.id} value={category.id}>
                  {category.icon} {translateCategoryName(category.name, locale as 'pt-br' | 'en')}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t('table.date')}</TableHead>
                <TableHead>{t('table.description')}</TableHead>
                <TableHead>{t('table.category')}</TableHead>
                <TableHead>{t('table.paymentMethod')}</TableHead>
                <TableHead className="text-right">{t('table.amount')}</TableHead>
                <TableHead className="text-right">{t('table.actions')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredTransactions.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center text-muted-foreground">
                    {t('transaction.noTransactions')}
                  </TableCell>
                </TableRow>
              ) : (
                filteredTransactions.map((transaction) => (
                  <TableRow key={transaction.id}>
                    <TableCell className="font-medium">{format(parseISO(transaction.date), "MMM dd, yyyy")}</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <span>{transaction.description || "-"}</span>
                        {transaction.metadata?.auto_generated && (
                          <Badge variant="secondary" className="text-xs">
                            {t('transaction.autoGenerated')}
                          </Badge>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <span className="inline-flex items-center gap-1">
                        {transaction.category?.icon} {transaction.category?.name && translateCategoryName(transaction.category.name, locale as 'pt-br' | 'en')}
                      </span>
                    </TableCell>
                    <TableCell className="capitalize">
                      {paymentMethods.find(pm => pm.id === transaction.payment_method_id)?.name || "-"}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex items-center justify-end gap-2">
                        <span
                          className={
                            transaction.type === "income" ? "text-green-600 font-semibold" : "text-red-600 font-semibold"
                          }
                        >
                          {transaction.type === "income" ? "+" : "-"}{formatCurrency(transaction.amount, locale as 'pt-br' | 'en')}
                        </span>
                        {/* Display statement period badge for Credit Mode transactions */}
                        {(() => {
                          const badgeInfo = badgeMap.get(transaction.id)
                          if (badgeInfo && badgeInfo.shouldDisplay) {
                            return <StatementBadge period={badgeInfo.period} />
                          }
                          return null
                        })()}
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <TransactionDialog
                          categories={categories}
                          paymentMethods={paymentMethods}
                          transaction={transaction}
                          trigger={
                            <Button variant="ghost" size="icon">
                              <EditIcon className="h-4 w-4" />
                            </Button>
                          }
                        />
                        <Button variant="ghost" size="icon" onClick={() => handleDelete(transaction)}>
                          <TrashIcon className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  )
}
